// Code generated by "stringer -type=FormatKind"; DO NOT EDIT.

package jwx

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _FormatKind_name = "InvalidFormatUnknownFormatJWEJWSJWKJWKSJWT"

var _FormatKind_index = [...]uint8{0, 13, 26, 29, 32, 35, 39, 42}

func (i FormatKind) String() string { _ = "STUB: not implemented"; return "" }
