// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT.

package jwa

import (
	"fmt"
	"sync"
)

var muAllCompressionAlgorithm sync.RWMutex
var allCompressionAlgorithm = map[string]CompressionAlgorithm{}
var muListCompressionAlgorithm sync.RWMutex
var listCompressionAlgorithm []CompressionAlgorithm
var builtinCompressionAlgorithm = map[string]struct{}{}

func init() {
	// builtin values for CompressionAlgorithm
	algorithms := make([]CompressionAlgorithm, 2)
	algorithms[0] = NewCompressionAlgorithm("DEF")
	algorithms[1] = NewCompressionAlgorithm("")

	if err := RegisterCompressionAlgorithm(algorithms...); err != nil {
		panic(fmt.Sprintf("jwa: failed to register builtin CompressionAlgorithm: %s", err))
	}
	for _, alg := range algorithms {
		builtinCompressionAlgorithm[alg.String()] = struct{}{}
	}
}

// Deflate returns an object representing the "DEF" content compression algorithm value. Using this value specifies that the content should be compressed using DEFLATE (RFC 1951).
func Deflate() CompressionAlgorithm { _ = "STUB: not implemented"; return *new(CompressionAlgorithm) }

// NoCompress returns an object representing an empty compression algorithm value. Using this value specifies that the content should not be compressed.
func NoCompress() CompressionAlgorithm {
	_ = "STUB: not implemented"
	return *new(CompressionAlgorithm)
}

func lookupBuiltinCompressionAlgorithm(name string) CompressionAlgorithm {
	_ = "STUB: not implemented"
	return *new(CompressionAlgorithm)
}

// CompressionAlgorithm represents the compression algorithms as described in https://tools.ietf.org/html/rfc7518#section-7.3
type CompressionAlgorithm struct {
	name       string
	deprecated bool
}

func (s CompressionAlgorithm) String() string {
	_ = "STUB: not implemented"

	// IsDeprecated returns true if the CompressionAlgorithm object is deprecated.
	return ""
}

func (s CompressionAlgorithm) IsDeprecated() bool { _ = "STUB: not implemented"; return false }

// EmptyCompressionAlgorithm returns an empty CompressionAlgorithm object, used as a zero value.
func EmptyCompressionAlgorithm() CompressionAlgorithm {
	_ = "STUB: not implemented"
	return *new(CompressionAlgorithm)
}

// NewCompressionAlgorithm creates a new CompressionAlgorithm object with the given name.
func NewCompressionAlgorithm(name string, options ...NewAlgorithmOption) CompressionAlgorithm {
	_ = "STUB: not implemented"
	return *new(CompressionAlgorithm)
}

// LookupCompressionAlgorithm returns the CompressionAlgorithm object for the given name.
func LookupCompressionAlgorithm(name string) (CompressionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(CompressionAlgorithm), false
}

// RegisterCompressionAlgorithm registers a new CompressionAlgorithm. The signature value must be immutable
// and safe to be used by multiple goroutines, as it is going to be shared with all other users of this library.
//
// Registration is process-global. Built-in identifiers such as RS256 are
// reserved and cannot be replaced by callers after init has completed; use a
// distinct name for third-party algorithms.
func RegisterCompressionAlgorithm(algorithms ...CompressionAlgorithm) error {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterCompressionAlgorithm unregisters a CompressionAlgorithm from its known database.
// Non-existent entries, as well as built-in algorithms will silently be ignored.
func UnregisterCompressionAlgorithm(algorithms ...CompressionAlgorithm) {
	_ = "STUB: not implemented"
	return
}

func rebuildCompressionAlgorithmLocked() { _ = "STUB: not implemented"; return }

// CompressionAlgorithms returns a list of all available values for CompressionAlgorithm.
func CompressionAlgorithms() []CompressionAlgorithm { _ = "STUB: not implemented"; return nil }

// MarshalJSON serializes the CompressionAlgorithm object to a JSON string.
func (s CompressionAlgorithm) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON deserializes the JSON string to a CompressionAlgorithm object.
func (s *CompressionAlgorithm) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}
