// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT.

package jwa

import (
	"fmt"

	"github.com/lestrrat-go/jwx/v4/internal/tokens"
)

func init() {
	// builtin values for ContentEncryptionAlgorithm
	algorithms := make([]ContentEncryptionAlgorithm, 6)
	algorithms[0] = NewContentEncryptionAlgorithm(tokens.A128CBC_HS256)
	algorithms[1] = NewContentEncryptionAlgorithm(tokens.A128GCM)
	algorithms[2] = NewContentEncryptionAlgorithm(tokens.A192CBC_HS384)
	algorithms[3] = NewContentEncryptionAlgorithm(tokens.A192GCM)
	algorithms[4] = NewContentEncryptionAlgorithm(tokens.A256CBC_HS512)
	algorithms[5] = NewContentEncryptionAlgorithm(tokens.A256GCM)

	if err := RegisterContentEncryptionAlgorithm(algorithms...); err != nil {
		panic(fmt.Sprintf("jwa: failed to register builtin ContentEncryptionAlgorithm: %s", err))
	}
	for _, alg := range algorithms {
		markBuiltin(alg.String())
	}
}

// A128CBC_HS256 returns an object representing A128CBC-HS256. Using this value specifies that the content should be encrypted using AES-CBC + HMAC-SHA256 (128).
func A128CBC_HS256() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// A128GCM returns an object representing A128GCM. Using this value specifies that the content should be encrypted using AES-GCM (128).
func A128GCM() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// A192CBC_HS384 returns an object representing A192CBC-HS384. Using this value specifies that the content should be encrypted using AES-CBC + HMAC-SHA384 (192).
func A192CBC_HS384() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// A192GCM returns an object representing A192GCM. Using this value specifies that the content should be encrypted using AES-GCM (192).
func A192GCM() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// A256CBC_HS512 returns an object representing A256CBC-HS512. Using this value specifies that the content should be encrypted using AES-CBC + HMAC-SHA512 (256).
func A256CBC_HS512() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// A256GCM returns an object representing A256GCM. Using this value specifies that the content should be encrypted using AES-GCM (256).
func A256GCM() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

func lookupBuiltinContentEncryptionAlgorithm(name string) ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// ContentEncryptionAlgorithm represents the various encryption algorithms as described in https://tools.ietf.org/html/rfc7518#section-5
type ContentEncryptionAlgorithm struct {
	name       string
	deprecated bool
}

func (s ContentEncryptionAlgorithm) String() string {
	_ = "STUB: not implemented"

	// IsDeprecated returns true if the ContentEncryptionAlgorithm object is deprecated.
	return ""
}

func (s ContentEncryptionAlgorithm) IsDeprecated() bool { _ = "STUB: not implemented"; return false }

// EmptyContentEncryptionAlgorithm returns an empty ContentEncryptionAlgorithm object, used as a zero value.
func EmptyContentEncryptionAlgorithm() ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// NewContentEncryptionAlgorithm creates a new ContentEncryptionAlgorithm object with the given name.
func NewContentEncryptionAlgorithm(name string, options ...NewAlgorithmOption) ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm)
}

// LookupContentEncryptionAlgorithm returns the ContentEncryptionAlgorithm object for the given name.
func LookupContentEncryptionAlgorithm(name string) (ContentEncryptionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(ContentEncryptionAlgorithm), false
}

// RegisterContentEncryptionAlgorithm registers a new ContentEncryptionAlgorithm. The signature value must be immutable
// and safe to be used by multiple goroutines, as it is going to be shared with all other users of this library.
//
// Registration is process-global. Built-in identifiers such as RS256 are
// reserved and cannot be replaced by callers after init has completed; use a
// distinct name for third-party algorithms.
//
// SignatureAlgorithm, KeyEncryptionAlgorithm, and ContentEncryptionAlgorithm
// share a single algorithm-name namespace so that KeyAlgorithmFrom can
// resolve unambiguously. Registering a name that is already registered as a
// different kind returns an error naming both the existing and the requested
// kind.
func RegisterContentEncryptionAlgorithm(algorithms ...ContentEncryptionAlgorithm) error {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterContentEncryptionAlgorithm unregisters a ContentEncryptionAlgorithm from its known database.
// Non-existent entries, as well as built-in algorithms will silently be ignored.
func UnregisterContentEncryptionAlgorithm(algorithms ...ContentEncryptionAlgorithm) {
	_ = "STUB: not implemented"
	return
}

// ContentEncryptionAlgorithms returns a list of all available values for ContentEncryptionAlgorithm.
func ContentEncryptionAlgorithms() []ContentEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON serializes the ContentEncryptionAlgorithm object to a JSON string.
func (s ContentEncryptionAlgorithm) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON deserializes the JSON string to a ContentEncryptionAlgorithm object.
func (s *ContentEncryptionAlgorithm) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}
