// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT.

package jwa

import (
	"fmt"
	"sync"
)

var muAllEllipticCurveAlgorithm sync.RWMutex
var allEllipticCurveAlgorithm = map[string]EllipticCurveAlgorithm{}
var muListEllipticCurveAlgorithm sync.RWMutex
var listEllipticCurveAlgorithm []EllipticCurveAlgorithm
var builtinEllipticCurveAlgorithm = map[string]struct{}{}

func init() {
	// builtin values for EllipticCurveAlgorithm
	algorithms := make([]EllipticCurveAlgorithm, 6)
	algorithms[0] = NewEllipticCurveAlgorithm("Ed25519")
	algorithms[1] = NewEllipticCurveAlgorithm("P-256")
	algorithms[2] = NewEllipticCurveAlgorithm("P-384")
	algorithms[3] = NewEllipticCurveAlgorithm("P-521")
	algorithms[4] = NewEllipticCurveAlgorithm("X25519")
	algorithms[5] = NewEllipticCurveAlgorithm("X448")

	if err := RegisterEllipticCurveAlgorithm(algorithms...); err != nil {
		panic(fmt.Sprintf("jwa: failed to register builtin EllipticCurveAlgorithm: %s", err))
	}
	for _, alg := range algorithms {
		builtinEllipticCurveAlgorithm[alg.String()] = struct{}{}
	}
}

// Ed25519 returns an object representing Ed25519 algorithm for EdDSA operations.
func Ed25519() EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

var invalidEllipticCurve = NewEllipticCurveAlgorithm("P-invalid")

// InvalidEllipticCurve returns an object representing an invalid elliptic curve.
func InvalidEllipticCurve() EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

// P256 returns an object representing P-256 algorithm for ECDSA operations.
func P256() EllipticCurveAlgorithm { _ = "STUB: not implemented"; return *new(EllipticCurveAlgorithm) }

// P384 returns an object representing P-384 algorithm for ECDSA operations.
func P384() EllipticCurveAlgorithm { _ = "STUB: not implemented"; return *new(EllipticCurveAlgorithm) }

// P521 returns an object representing P-521 algorithm for ECDSA operations.
func P521() EllipticCurveAlgorithm { _ = "STUB: not implemented"; return *new(EllipticCurveAlgorithm) }

// X25519 returns an object representing X25519 algorithm for ECDH operations.
func X25519() EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

// X448 returns an object representing X448 algorithm for ECDH operations.
func X448() EllipticCurveAlgorithm { _ = "STUB: not implemented"; return *new(EllipticCurveAlgorithm) }

func lookupBuiltinEllipticCurveAlgorithm(name string) EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

// EllipticCurveAlgorithm represents the algorithms used for EC keys
type EllipticCurveAlgorithm struct {
	name       string
	deprecated bool
}

func (s EllipticCurveAlgorithm) String() string {
	_ = "STUB: not implemented"

	// IsDeprecated returns true if the EllipticCurveAlgorithm object is deprecated.
	return ""
}

func (s EllipticCurveAlgorithm) IsDeprecated() bool { _ = "STUB: not implemented"; return false }

// EmptyEllipticCurveAlgorithm returns an empty EllipticCurveAlgorithm object, used as a zero value.
func EmptyEllipticCurveAlgorithm() EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

// NewEllipticCurveAlgorithm creates a new EllipticCurveAlgorithm object with the given name.
func NewEllipticCurveAlgorithm(name string, options ...NewAlgorithmOption) EllipticCurveAlgorithm {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm)
}

// LookupEllipticCurveAlgorithm returns the EllipticCurveAlgorithm object for the given name.
func LookupEllipticCurveAlgorithm(name string) (EllipticCurveAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(EllipticCurveAlgorithm), false
}

// RegisterEllipticCurveAlgorithm registers a new EllipticCurveAlgorithm. The signature value must be immutable
// and safe to be used by multiple goroutines, as it is going to be shared with all other users of this library.
//
// Registration is process-global. Built-in identifiers such as RS256 are
// reserved and cannot be replaced by callers after init has completed; use a
// distinct name for third-party algorithms.
func RegisterEllipticCurveAlgorithm(algorithms ...EllipticCurveAlgorithm) error {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterEllipticCurveAlgorithm unregisters a EllipticCurveAlgorithm from its known database.
// Non-existent entries, as well as built-in algorithms will silently be ignored.
func UnregisterEllipticCurveAlgorithm(algorithms ...EllipticCurveAlgorithm) {
	_ = "STUB: not implemented"
	return
}

func rebuildEllipticCurveAlgorithmLocked() { _ = "STUB: not implemented"; return }

// EllipticCurveAlgorithms returns a list of all available values for EllipticCurveAlgorithm.
func EllipticCurveAlgorithms() []EllipticCurveAlgorithm { _ = "STUB: not implemented"; return nil }

// MarshalJSON serializes the EllipticCurveAlgorithm object to a JSON string.
func (s EllipticCurveAlgorithm) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON deserializes the JSON string to a EllipticCurveAlgorithm object.
func (s *EllipticCurveAlgorithm) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}
