// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT.

package jwa

import (
	"fmt"

	"github.com/lestrrat-go/jwx/v4/internal/tokens"
)

func init() {
	// builtin values for KeyEncryptionAlgorithm
	algorithms := make([]KeyEncryptionAlgorithm, 25)
	algorithms[0] = NewKeyEncryptionAlgorithm(tokens.A128GCMKW, WithIsSymmetric(true))
	algorithms[1] = NewKeyEncryptionAlgorithm(tokens.A128KW, WithIsSymmetric(true))
	algorithms[2] = NewKeyEncryptionAlgorithm(tokens.A192GCMKW, WithIsSymmetric(true))
	algorithms[3] = NewKeyEncryptionAlgorithm(tokens.A192KW, WithIsSymmetric(true))
	algorithms[4] = NewKeyEncryptionAlgorithm(tokens.A256GCMKW, WithIsSymmetric(true))
	algorithms[5] = NewKeyEncryptionAlgorithm(tokens.A256KW, WithIsSymmetric(true))
	algorithms[6] = NewKeyEncryptionAlgorithm(tokens.DIRECT, WithIsSymmetric(true))
	algorithms[7] = NewKeyEncryptionAlgorithm(tokens.ECDH_ES)
	algorithms[8] = NewKeyEncryptionAlgorithm(tokens.ECDH_ES_A128KW)
	algorithms[9] = NewKeyEncryptionAlgorithm(tokens.ECDH_ES_A192KW)
	algorithms[10] = NewKeyEncryptionAlgorithm(tokens.ECDH_ES_A256KW)
	algorithms[11] = NewKeyEncryptionAlgorithm(tokens.HPKE_0_KE)
	algorithms[12] = NewKeyEncryptionAlgorithm(tokens.HPKE_1_KE)
	algorithms[13] = NewKeyEncryptionAlgorithm(tokens.HPKE_2_KE)
	algorithms[14] = NewKeyEncryptionAlgorithm(tokens.HPKE_3_KE)
	algorithms[15] = NewKeyEncryptionAlgorithm(tokens.HPKE_4_KE)
	algorithms[16] = NewKeyEncryptionAlgorithm(tokens.HPKE_7_KE)
	algorithms[17] = NewKeyEncryptionAlgorithm(tokens.PBES2_HS256_A128KW, WithIsSymmetric(true))
	algorithms[18] = NewKeyEncryptionAlgorithm(tokens.PBES2_HS384_A192KW, WithIsSymmetric(true))
	algorithms[19] = NewKeyEncryptionAlgorithm(tokens.PBES2_HS512_A256KW, WithIsSymmetric(true))
	algorithms[20] = NewKeyEncryptionAlgorithm(tokens.RSA1_5, WithDeprecated(true))
	algorithms[21] = NewKeyEncryptionAlgorithm(tokens.RSA_OAEP)
	algorithms[22] = NewKeyEncryptionAlgorithm(tokens.RSA_OAEP_256)
	algorithms[23] = NewKeyEncryptionAlgorithm(tokens.RSA_OAEP_384)
	algorithms[24] = NewKeyEncryptionAlgorithm(tokens.RSA_OAEP_512)

	if err := RegisterKeyEncryptionAlgorithm(algorithms...); err != nil {
		panic(fmt.Sprintf("jwa: failed to register builtin KeyEncryptionAlgorithm: %s", err))
	}
	for _, alg := range algorithms {
		markBuiltin(alg.String())
	}
}

// A128GCMKW returns an object representing AES-GCM key wrap (128) key encryption algorithm.
func A128GCMKW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// A128KW returns an object representing AES key wrap (128) key encryption algorithm.
func A128KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// A192GCMKW returns an object representing AES-GCM key wrap (192) key encryption algorithm.
func A192GCMKW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// A192KW returns an object representing AES key wrap (192) key encryption algorithm.
func A192KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// A256GCMKW returns an object representing AES-GCM key wrap (256) key encryption algorithm.
func A256GCMKW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// A256KW returns an object representing AES key wrap (256) key encryption algorithm.
func A256KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// DIRECT returns an object representing Direct key encryption algorithm.
func DIRECT() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// ECDH_ES returns an object representing ECDH-ES key encryption algorithm.
func ECDH_ES() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// ECDH_ES_A128KW returns an object representing ECDH-ES + AES key wrap (128) key encryption algorithm.
func ECDH_ES_A128KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// ECDH_ES_A192KW returns an object representing ECDH-ES + AES key wrap (192) key encryption algorithm.
func ECDH_ES_A192KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// ECDH_ES_A256KW returns an object representing ECDH-ES + AES key wrap (256) key encryption algorithm.
func ECDH_ES_A256KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_0_KE returns an object representing HPKE-0-KE key encryption (DHKEM(P-256) + HKDF-SHA256 + AES-128-GCM). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_0_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_1_KE returns an object representing HPKE-1-KE key encryption (DHKEM(P-384) + HKDF-SHA384 + AES-256-GCM). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_1_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_2_KE returns an object representing HPKE-2-KE key encryption (DHKEM(P-521) + HKDF-SHA512 + AES-256-GCM). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_2_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_3_KE returns an object representing HPKE-3-KE key encryption (DHKEM(X25519) + HKDF-SHA256 + AES-128-GCM). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_3_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_4_KE returns an object representing HPKE-4-KE key encryption (DHKEM(X25519) + HKDF-SHA256 + ChaCha20Poly1305). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_4_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// HPKE_7_KE returns an object representing HPKE-7-KE key encryption (DHKEM(P-256) + HKDF-SHA256 + AES-256-GCM). Based on draft-ietf-jose-hpke-encrypt-16: API is not yet stable.
func HPKE_7_KE() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// PBES2_HS256_A128KW returns an object representing PBES2 + HMAC-SHA256 + AES key wrap (128) key encryption algorithm.
func PBES2_HS256_A128KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// PBES2_HS384_A192KW returns an object representing PBES2 + HMAC-SHA384 + AES key wrap (192) key encryption algorithm.
func PBES2_HS384_A192KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// PBES2_HS512_A256KW returns an object representing PBES2 + HMAC-SHA512 + AES key wrap (256) key encryption algorithm.
func PBES2_HS512_A256KW() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// RSA1_5 returns an object representing RSA-PKCS1v1.5 key encryption algorithm.
func RSA1_5() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// RSA_OAEP returns an object representing RSA-OAEP-SHA1 key encryption algorithm.
func RSA_OAEP() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// RSA_OAEP_256 returns an object representing RSA-OAEP-SHA256 key encryption algorithm.
func RSA_OAEP_256() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// RSA_OAEP_384 returns an object representing RSA-OAEP-SHA384 key encryption algorithm.
func RSA_OAEP_384() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// RSA_OAEP_512 returns an object representing RSA-OAEP-SHA512 key encryption algorithm.
func RSA_OAEP_512() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

func lookupBuiltinKeyEncryptionAlgorithm(name string) KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// KeyEncryptionAlgorithm represents the various encryption algorithms as described in https://tools.ietf.org/html/rfc7518#section-4.1
type KeyEncryptionAlgorithm struct {
	name        string
	deprecated  bool
	isSymmetric bool
}

func (s KeyEncryptionAlgorithm) String() string {
	_ = "STUB: not implemented"

	// IsDeprecated returns true if the KeyEncryptionAlgorithm object is deprecated.
	return ""
}

func (s KeyEncryptionAlgorithm) IsDeprecated() bool { _ = "STUB: not implemented"; return false }

// IsSymmetric returns true if the KeyEncryptionAlgorithm object is symmetric. Symmetric algorithms use the same key for both encryption and decryption.
func (s KeyEncryptionAlgorithm) IsSymmetric() bool { _ = "STUB: not implemented"; return false }

// EmptyKeyEncryptionAlgorithm returns an empty KeyEncryptionAlgorithm object, used as a zero value.
func EmptyKeyEncryptionAlgorithm() KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// NewKeyEncryptionAlgorithm creates a new KeyEncryptionAlgorithm object with the given name.
func NewKeyEncryptionAlgorithm(name string, options ...NewKeyEncryptionAlgorithmOption) KeyEncryptionAlgorithm {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm)
}

// LookupKeyEncryptionAlgorithm returns the KeyEncryptionAlgorithm object for the given name.
func LookupKeyEncryptionAlgorithm(name string) (KeyEncryptionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(KeyEncryptionAlgorithm), false
}

// RegisterKeyEncryptionAlgorithm registers a new KeyEncryptionAlgorithm. The signature value must be immutable
// and safe to be used by multiple goroutines, as it is going to be shared with all other users of this library.
//
// Registration is process-global. Built-in identifiers such as RS256 are
// reserved and cannot be replaced by callers after init has completed; use a
// distinct name for third-party algorithms.
//
// SignatureAlgorithm, KeyEncryptionAlgorithm, and ContentEncryptionAlgorithm
// share a single algorithm-name namespace so that KeyAlgorithmFrom can
// resolve unambiguously. Registering a name that is already registered as a
// different kind returns an error naming both the existing and the requested
// kind.
func RegisterKeyEncryptionAlgorithm(algorithms ...KeyEncryptionAlgorithm) error {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterKeyEncryptionAlgorithm unregisters a KeyEncryptionAlgorithm from its known database.
// Non-existent entries, as well as built-in algorithms will silently be ignored.
func UnregisterKeyEncryptionAlgorithm(algorithms ...KeyEncryptionAlgorithm) {
	_ = "STUB: not implemented"
	return
}

// KeyEncryptionAlgorithms returns a list of all available values for KeyEncryptionAlgorithm.
func KeyEncryptionAlgorithms() []KeyEncryptionAlgorithm { _ = "STUB: not implemented"; return nil }

// MarshalJSON serializes the KeyEncryptionAlgorithm object to a JSON string.
func (s KeyEncryptionAlgorithm) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON deserializes the JSON string to a KeyEncryptionAlgorithm object.
func (s *KeyEncryptionAlgorithm) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}
