// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT.

package jwa

import (
	"fmt"
	"sync"
)

var muAllKeyType sync.RWMutex
var allKeyType = map[string]KeyType{}
var muListKeyType sync.RWMutex
var listKeyType []KeyType
var builtinKeyType = map[string]struct{}{}

func init() {
	// builtin values for KeyType
	algorithms := make([]KeyType, 5)
	algorithms[0] = NewKeyType("AKP")
	algorithms[1] = NewKeyType("EC")
	algorithms[2] = NewKeyType("OKP")
	algorithms[3] = NewKeyType("oct")
	algorithms[4] = NewKeyType("RSA")

	if err := RegisterKeyType(algorithms...); err != nil {
		panic(fmt.Sprintf("jwa: failed to register builtin KeyType: %s", err))
	}
	for _, alg := range algorithms {
		builtinKeyType[alg.String()] = struct{}{}
	}
}

// AKP returns an object representing AKP. Algorithm Key Pair (post-quantum KEM/signature keys)
func AKP() KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

// EC returns an object representing EC. Elliptic Curve
func EC() KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

var invalidKeyType = NewKeyType("")

// InvalidKeyType returns an object representing invalid key type. Invalid KeyType
func InvalidKeyType() KeyType {
	_ = "STUB: not implemented"
	return *

	// OKP returns an object representing OKP. Octet string key pairs
	new(KeyType)
}

func OKP() KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

// OctetSeq returns an object representing oct. Octet sequence (used to represent symmetric keys)
func OctetSeq() KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

// RSA returns an object representing RSA. RSA
func RSA() KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

func lookupBuiltinKeyType(name string) KeyType { _ = "STUB: not implemented"; return *new(KeyType) }

// KeyType represents the key type ("kty") that are supported
type KeyType struct {
	name       string
	deprecated bool
}

func (s KeyType) String() string {
	_ = "STUB: not implemented"

	// IsDeprecated returns true if the KeyType object is deprecated.
	return ""
}

func (s KeyType) IsDeprecated() bool { _ = "STUB: not implemented"; return false }

// EmptyKeyType returns an empty KeyType object, used as a zero value.
func EmptyKeyType() KeyType {
	_ = "STUB: not implemented"

	// NewKeyType creates a new KeyType object with the given name.
	return *new(KeyType)
}

func NewKeyType(name string, options ...NewAlgorithmOption) KeyType {
	_ = "STUB: not implemented"
	return *new(KeyType)
}

// LookupKeyType returns the KeyType object for the given name.
func LookupKeyType(name string) (KeyType, bool) {
	_ = "STUB: not implemented"
	return *new(KeyType), false
}

// RegisterKeyType registers a new KeyType. The signature value must be immutable
// and safe to be used by multiple goroutines, as it is going to be shared with all other users of this library.
//
// Registration is process-global. Built-in identifiers such as RS256 are
// reserved and cannot be replaced by callers after init has completed; use a
// distinct name for third-party algorithms.
func RegisterKeyType(algorithms ...KeyType) error { _ = "STUB: not implemented"; return nil }

// UnregisterKeyType unregisters a KeyType from its known database.
// Non-existent entries, as well as built-in algorithms will silently be ignored.
func UnregisterKeyType(algorithms ...KeyType) { _ = "STUB: not implemented"; return }

func rebuildKeyTypeLocked() { _ = "STUB: not implemented"; return }

// KeyTypes returns a list of all available values for KeyType.
func KeyTypes() []KeyType { _ = "STUB: not implemented"; return nil }

// MarshalJSON serializes the KeyType object to a JSON string.
func (s KeyType) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON deserializes the JSON string to a KeyType object.
func (s *KeyType) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }
