// Code generated by tools/cmd/genoptions/main.go. DO NOT EDIT.

package jwa

import (
	"github.com/lestrrat-go/option/v3"
)

type Option = option.Interface

// NewAlgorithmOption represents an option that can be passed to any of the constructor functions
type NewAlgorithmOption interface {
	Option
	newSignatureAlgorithmOption()
	newKeyEncryptionAlgorithmOption()
	newSignatureKeyEncryptionAlgorithmOption()
}

type newAlgorithmOption struct {
	Option
}

func (*newAlgorithmOption) newSignatureAlgorithmOption() { _ = "STUB: not implemented"; return }

func (*newAlgorithmOption) newKeyEncryptionAlgorithmOption() { _ = "STUB: not implemented"; return }

func (*newAlgorithmOption) newSignatureKeyEncryptionAlgorithmOption() {
	_ = "STUB: not implemented"

	// NewKeyEncryptionAlgorithmOption represents an option that can be passed to the NewKeyEncryptionAlgorithm
	return
}

type NewKeyEncryptionAlgorithmOption interface {
	Option
	newKeyEncryptionAlgorithmOption()
}

type newKeyEncryptionAlgorithmOption struct {
	Option
}

func (*newKeyEncryptionAlgorithmOption) newKeyEncryptionAlgorithmOption() {
	_ = "STUB: not implemented"

	// NewSignatureAlgorithmOption represents an option that can be passed to the NewSignatureAlgorithm
	return
}

type NewSignatureAlgorithmOption interface {
	Option
	newSignatureAlgorithmOption()
}

type newSignatureAlgorithmOption struct {
	Option
}

func (*newSignatureAlgorithmOption) newSignatureAlgorithmOption() {
	_ = "STUB: not implemented"

	// NewSignatureKeyEncryptionAlgorithmOption represents an option that can be passed to both
	// NewSignatureAlgorithm and NewKeyEncryptionAlgorithm
	return
}

type NewSignatureKeyEncryptionAlgorithmOption interface {
	Option
	newSignatureAlgorithmOption()
	newKeyEncryptionAlgorithmOption()
}

type newSignatureKeyEncryptionAlgorithmOption struct {
	Option
}

func (*newSignatureKeyEncryptionAlgorithmOption) newSignatureAlgorithmOption() {
	_ = "STUB: not implemented"
	return
}

func (*newSignatureKeyEncryptionAlgorithmOption) newKeyEncryptionAlgorithmOption() {
	_ = "STUB: not implemented"
	return
}

type identDeprecated struct{}
type identIsSymmetric struct{}

func (identDeprecated) String() string { _ = "STUB: not implemented"; return "" }

func (identIsSymmetric) String() string { _ = "STUB: not implemented"; return "" }

// WithDeprecated specifies that the algorithm is deprecated. In order to
// un-deprecate an algorithm, you will have to create a new algorithm
// with the same values but with the Deprecated option set to false, and
// then call RegisterXXXXAlgorithm with the new algorithm.
func WithDeprecated(v bool) NewAlgorithmOption {
	_ = "STUB: not implemented"
	return *new(NewAlgorithmOption)
}

// IsSymmetric specifies that the algorithm is symmetric
func WithIsSymmetric(v bool) NewSignatureKeyEncryptionAlgorithmOption {
	_ = "STUB: not implemented"
	return *new(NewSignatureKeyEncryptionAlgorithmOption)
}
