// Code generated by tools/cmd/genjwt/main.go. DO NOT EDIT.

package openid

import (
	"sync"
	"time"
)

// Builder is a convenience wrapper around the New() constructor
// and the Set() methods to assign values to Token claims.
// Users can successively call Claim() on the Builder, and have it
// construct the Token when Build() is called. This alleviates the
// need for the user to check for the return value of every single
// Set() method call.
// Note that each call to Claim() overwrites the value set from the
// previous call.
type Builder struct {
	mu     sync.Mutex
	claims map[string]any
}

func NewBuilder() *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) init() {
	if b.claims == nil {
		b.claims = make(map[string]any)
	}
}

func (b *Builder) Claim(name string, value any) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Address(v *AddressClaim) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Audience(v []string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Birthdate(v *BirthdateClaim) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Email(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) EmailVerified(v bool) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Expiration(v time.Time) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) FamilyName(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Gender(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) GivenName(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) IssuedAt(v time.Time) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Issuer(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) JwtID(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Locale(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) MiddleName(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Name(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Nickname(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) NotBefore(v time.Time) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) PhoneNumber(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) PhoneNumberVerified(v bool) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Picture(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) PreferredUsername(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Profile(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Subject(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) UpdatedAt(v time.Time) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Website(v string) *Builder { _ = "STUB: not implemented"; return nil }

func (b *Builder) Zoneinfo(v string) *Builder { _ = "STUB: not implemented"; return nil }

// Build creates a new token based on the claims that the builder has received
// so far. If a claim cannot be set, then the method returns a nil Token with
// a en error as a second return value
//
// Once `Build()` is called, all claims are cleared from the Builder, and the
// Builder can be reused to build another token
func (b *Builder) Build() (Token, error) { _ = "STUB: not implemented"; return *new(Token), nil }
