// Code generated by tools/cmd/genjwt/main.go. DO NOT EDIT.

package openid

import (
	"iter"
	"sync"
	"time"

	"github.com/lestrrat-go/jwx/v4/jwt"
	"github.com/lestrrat-go/jwx/v4/jwt/internal/types"
)

const (
	AddressKey             = "address"
	AudienceKey            = "aud"
	BirthdateKey           = "birthdate"
	EmailKey               = "email"
	EmailVerifiedKey       = "email_verified"
	ExpirationKey          = "exp"
	FamilyNameKey          = "family_name"
	GenderKey              = "gender"
	GivenNameKey           = "given_name"
	IssuedAtKey            = "iat"
	IssuerKey              = "iss"
	JwtIDKey               = "jti"
	LocaleKey              = "locale"
	MiddleNameKey          = "middle_name"
	NameKey                = "name"
	NicknameKey            = "nickname"
	NotBeforeKey           = "nbf"
	PhoneNumberKey         = "phone_number"
	PhoneNumberVerifiedKey = "phone_number_verified"
	PictureKey             = "picture"
	PreferredUsernameKey   = "preferred_username"
	ProfileKey             = "profile"
	SubjectKey             = "sub"
	UpdatedAtKey           = "updated_at"
	WebsiteKey             = "website"
	ZoneinfoKey            = "zoneinfo"
)

type Token interface {
	// Address returns the value for "address" field of the token
	Address() (*AddressClaim, bool)

	// Audience returns the value for "aud" field of the token
	Audience() ([]string, bool)

	// Birthdate returns the value for "birthdate" field of the token
	Birthdate() (*BirthdateClaim, bool)

	// Email returns the value for "email" field of the token
	Email() (string, bool)

	// EmailVerified returns the value for "email_verified" field of the token
	EmailVerified() (bool, bool)

	// Expiration returns the value for "exp" field of the token
	Expiration() (time.Time, bool)

	// FamilyName returns the value for "family_name" field of the token
	FamilyName() (string, bool)

	// Gender returns the value for "gender" field of the token
	Gender() (string, bool)

	// GivenName returns the value for "given_name" field of the token
	GivenName() (string, bool)

	// IssuedAt returns the value for "iat" field of the token
	IssuedAt() (time.Time, bool)

	// Issuer returns the value for "iss" field of the token
	Issuer() (string, bool)

	// JwtID returns the value for "jti" field of the token
	JwtID() (string, bool)

	// Locale returns the value for "locale" field of the token
	Locale() (string, bool)

	// MiddleName returns the value for "middle_name" field of the token
	MiddleName() (string, bool)

	// Name returns the value for "name" field of the token
	Name() (string, bool)

	// Nickname returns the value for "nickname" field of the token
	Nickname() (string, bool)

	// NotBefore returns the value for "nbf" field of the token
	NotBefore() (time.Time, bool)

	// PhoneNumber returns the value for "phone_number" field of the token
	PhoneNumber() (string, bool)

	// PhoneNumberVerified returns the value for "phone_number_verified" field of the token
	PhoneNumberVerified() (bool, bool)

	// Picture returns the value for "picture" field of the token
	Picture() (string, bool)

	// PreferredUsername returns the value for "preferred_username" field of the token
	PreferredUsername() (string, bool)

	// Profile returns the value for "profile" field of the token
	Profile() (string, bool)

	// Subject returns the value for "sub" field of the token
	Subject() (string, bool)

	// UpdatedAt returns the value for "updated_at" field of the token
	UpdatedAt() (time.Time, bool)

	// Website returns the value for "website" field of the token
	Website() (string, bool)

	// Zoneinfo returns the value for "zoneinfo" field of the token
	Zoneinfo() (string, bool)

	// Field returns the value of a claim by name, along with a boolean indicating
	// whether the claim was found. For standard claims, you can also use the
	// corresponding getter method, such as `Issuer()`, `Subject()`, etc.
	// For type-safe access to claims, use the `jwt.Get[T]()` generic accessor.
	Field(string) (any, bool)

	// Set assigns a value to the corresponding field in the token. Some
	// pre-defined fields such as `nbf`, `iat`, `iss` need their values to
	// be of a specific type. See the other getter methods in this interface
	// for the types of each of these fields
	Set(string, any) error

	// Has returns true if the specified claim has a value, even if
	// the value is empty-ish (e.g. 0, false, "")  as long as it has been
	// explicitly set.
	Has(string) bool
	Remove(string) error

	// Options returns the per-token options associated with this token.
	// The options set value will be copied when the token is cloned via `Clone()`
	// but it will not survive when the token goes through marshaling/unmarshaling
	// such as `json.Marshal` and `json.Unmarshal`
	Options() *jwt.TokenOptionSet
	Clone() (jwt.Token, error)
	Keys() []string
	// Claims returns an iterator over all claims (standard and private) in the token.
	Claims() iter.Seq2[string, any]
}
type stdToken struct {
	mu                  sync.RWMutex
	dc                  DecodeCtx          // per-object context for decoding
	options             jwt.TokenOptionSet // per-object option
	address             *AddressClaim
	audience            types.StringList // https://tools.ietf.org/html/rfc7519#section-4.1.3
	birthdate           *BirthdateClaim
	email               *string
	emailVerified       *bool
	expiration          *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.4
	familyName          *string
	gender              *string
	givenName           *string
	issuedAt            *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.6
	issuer              *string            // https://tools.ietf.org/html/rfc7519#section-4.1.1
	jwtID               *string            // https://tools.ietf.org/html/rfc7519#section-4.1.7
	locale              *string
	middleName          *string
	name                *string
	nickname            *string
	notBefore           *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.5
	phoneNumber         *string
	phoneNumberVerified *bool
	picture             *string
	preferredUsername   *string
	profile             *string
	subject             *string // https://tools.ietf.org/html/rfc7519#section-4.1.2
	updatedAt           *types.NumericDate
	website             *string
	zoneinfo            *string
	privateClaims       map[string]any
}

// New creates a standard token, with minimal knowledge of
// possible claims. Standard claims include"address", "aud", "birthdate", "email", "email_verified", "exp", "family_name", "gender", "given_name", "iat", "iss", "jti", "locale", "middle_name", "name", "nickname", "nbf", "phone_number", "phone_number_verified", "picture", "preferred_username", "profile", "sub", "updated_at", "website" and "zoneinfo".
// Convenience accessors are provided for these standard claims
func New() Token { _ = "STUB: not implemented"; return *new(Token) }

func (t *stdToken) Options() *jwt.TokenOptionSet { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (t *stdToken) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (t *stdToken) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) DecodeCtx() DecodeCtx { _ = "STUB: not implemented"; return *new(DecodeCtx) }

func (t *stdToken) SetDecodeCtx(v DecodeCtx) { _ = "STUB: not implemented"; return }

func (t *stdToken) setNoLock(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Address() (*AddressClaim, bool) { _ = "STUB: not implemented"; return nil, false }

func (t *stdToken) Audience() ([]string, bool) { _ = "STUB: not implemented"; return nil, false }

func (t *stdToken) Birthdate() (*BirthdateClaim, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (t *stdToken) Email() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) EmailVerified() (bool, bool) { _ = "STUB: not implemented"; return false, false }

func (t *stdToken) Expiration() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) FamilyName() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Gender() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) GivenName() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) IssuedAt() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) Issuer() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) JwtID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Locale() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) MiddleName() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Name() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Nickname() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) NotBefore() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) PhoneNumber() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) PhoneNumberVerified() (bool, bool) {
	_ = "STUB: not implemented"
	return false, false
}

func (t *stdToken) Picture() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) PreferredUsername() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Profile() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Subject() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) UpdatedAt() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) Website() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) Zoneinfo() (string, bool) { _ = "STUB: not implemented"; return "", false }

// PrivateClaims returns the underlying map of non-standard claims held by
// the token. The returned map is the live map used by the token, not a copy:
// callers must not mutate it, and must not read from it concurrently with
// Set/Remove or with unmarshaling on the same token. If you need a stable
// snapshot for concurrent use, copy the map (for example via maps.Clone)
// before iterating.
//
// To obtain a fresh token containing only the non-standard claims, use the
// jwxfilter companion module: jwtfilter.Standard().Reject(token) from
// github.com/jwx-go/jwxfilter/v4/jwtfilter (or openidfilter.Standard().Reject
// for openid.Token).
func (t *stdToken) PrivateClaims() map[string]any { _ = "STUB: not implemented"; return nil }

func (t *stdToken) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (t *stdToken) Keys() []string { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Claims() iter.Seq2[string, any] { _ = "STUB: not implemented"; return nil }

func (dst *stdToken) cloneFrom(src *stdToken) { _ = "STUB: not implemented"; return }

type claimPair struct {
	Name  string
	Value any
}

var claimPairPool = sync.Pool{
	New: func() any {
		return make([]claimPair, 0, 26)
	},
}

func getClaimPairList() []claimPair { _ = "STUB: not implemented"; return nil }

func putClaimPairList(list []claimPair) { _ = "STUB: not implemented"; return }

func (t *stdToken) makePairs() []claimPair { _ = "STUB: not implemented"; return nil }

func (t *stdToken) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
