// Code generated by tools/cmd/genjwk/main.go. DO NOT EDIT.

package jwk

import (
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk/internal/registry"
)

const (
	AKPPrivKey = "priv"
	AKPPubKey  = "pub"
)

// AKPPublicKey represents the public portion of an Algorithm Key Pair (AKP) JWK,
// used by post-quantum algorithms such as ML-DSA (FIPS 204) and ML-KEM (FIPS 203).
// ML-KEM support lives in the github.com/jwx-go/mlkem companion module.
type AKPPublicKey interface {
	Key
	Pub() ([]byte, bool)
}

type akpPublicKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	pub                    []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ AKPPublicKey = &akpPublicKey{}
var _ Key = &akpPublicKey{}

func newAKPPublicKey() *akpPublicKey { _ = "STUB: not implemented"; return nil }

func (h *akpPublicKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *akpPublicKey) rlock() { _ = "STUB: not implemented"; return }

func (h *akpPublicKey) runlock() { _ = "STUB: not implemented"; return }

func (h *akpPublicKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *akpPublicKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *akpPublicKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPublicKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *akpPublicKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPublicKey) Pub() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *akpPublicKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *akpPublicKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *akpPublicKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *akpPublicKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPublicKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *akpPublicKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *akpPublicKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *akpPublicKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *akpPublicKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *akpPublicKey) cloneFrom(src *akpPublicKey) { _ = "STUB: not implemented"; return }

func (k *akpPublicKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *akpPublicKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *akpPublicKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *akpPublicKey) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *akpPublicKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *akpPublicKey) Keys() []string { _ = "STUB: not implemented"; return nil }

// AKPPrivateKey represents the private portion of an Algorithm Key Pair (AKP) JWK,
// used by post-quantum algorithms such as ML-DSA (FIPS 204) and ML-KEM (FIPS 203).
// ML-KEM support lives in the github.com/jwx-go/mlkem companion module.
type AKPPrivateKey interface {
	Key
	Priv() ([]byte, bool)
	Pub() ([]byte, bool)
}

type akpPrivateKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	priv                   []byte
	pub                    []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ AKPPrivateKey = &akpPrivateKey{}
var _ Key = &akpPrivateKey{}

func newAKPPrivateKey() *akpPrivateKey { _ = "STUB: not implemented"; return nil }

func (h *akpPrivateKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *akpPrivateKey) rlock() { _ = "STUB: not implemented"; return }

func (h *akpPrivateKey) runlock() { _ = "STUB: not implemented"; return }

func (h *akpPrivateKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *akpPrivateKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *akpPrivateKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPrivateKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *akpPrivateKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPrivateKey) Priv() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *akpPrivateKey) Pub() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *akpPrivateKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *akpPrivateKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *akpPrivateKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *akpPrivateKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *akpPrivateKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *akpPrivateKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *akpPrivateKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *akpPrivateKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *akpPrivateKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *akpPrivateKey) cloneFrom(src *akpPrivateKey) { _ = "STUB: not implemented"; return }

func (k *akpPrivateKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *akpPrivateKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *akpPrivateKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *akpPrivateKey) UnmarshalJSON(buf []byte) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// consume closing '}'

func (h *akpPrivateKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *akpPrivateKey) Keys() []string { _ = "STUB: not implemented"; return nil }

func init() {
	registry.Register(jwa.AKP().String(), registry.Constructor{
		Public:  func() any { return newAKPPublicKey() },
		Private: func() any { return newAKPPrivateKey() },
	})
}
