// Code generated by tools/cmd/genjwk/main.go. DO NOT EDIT.

package jwk

import (
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk/internal/registry"
)

const (
	ECDSACrvKey = "crv"
	ECDSADKey   = "d"
	ECDSAXKey   = "x"
	ECDSAYKey   = "y"
)

type ECDSAPublicKey interface {
	Key
	Crv() (jwa.EllipticCurveAlgorithm, bool)
	X() ([]byte, bool)
	Y() ([]byte, bool)
}

type ecdsaPublicKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	crv                    *jwa.EllipticCurveAlgorithm
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	x                      []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	y                      []byte
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ ECDSAPublicKey = &ecdsaPublicKey{}
var _ Key = &ecdsaPublicKey{}

func newECDSAPublicKey() *ecdsaPublicKey { _ = "STUB: not implemented"; return nil }

func (h *ecdsaPublicKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *ecdsaPublicKey) rlock() { _ = "STUB: not implemented"; return }

func (h *ecdsaPublicKey) runlock() { _ = "STUB: not implemented"; return }

func (h *ecdsaPublicKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *ecdsaPublicKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *ecdsaPublicKey) Crv() (jwa.EllipticCurveAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.EllipticCurveAlgorithm), false
}

func (h *ecdsaPublicKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPublicKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *ecdsaPublicKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPublicKey) X() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *ecdsaPublicKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *ecdsaPublicKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *ecdsaPublicKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *ecdsaPublicKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPublicKey) Y() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *ecdsaPublicKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *ecdsaPublicKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *ecdsaPublicKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *ecdsaPublicKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *ecdsaPublicKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *ecdsaPublicKey) cloneFrom(src *ecdsaPublicKey) { _ = "STUB: not implemented"; return }

func (k *ecdsaPublicKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *ecdsaPublicKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *ecdsaPublicKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *ecdsaPublicKey) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *ecdsaPublicKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *ecdsaPublicKey) Keys() []string { _ = "STUB: not implemented"; return nil }

type ECDSAPrivateKey interface {
	Key
	Crv() (jwa.EllipticCurveAlgorithm, bool)
	D() ([]byte, bool)
	X() ([]byte, bool)
	Y() ([]byte, bool)
}

type ecdsaPrivateKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	crv                    *jwa.EllipticCurveAlgorithm
	d                      []byte
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	x                      []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	y                      []byte
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ ECDSAPrivateKey = &ecdsaPrivateKey{}
var _ Key = &ecdsaPrivateKey{}

func newECDSAPrivateKey() *ecdsaPrivateKey { _ = "STUB: not implemented"; return nil }

func (h *ecdsaPrivateKey) KeyType() jwa.KeyType {
	_ = "STUB: not implemented"
	return *new(jwa.KeyType)
}

func (h *ecdsaPrivateKey) rlock() { _ = "STUB: not implemented"; return }

func (h *ecdsaPrivateKey) runlock() { _ = "STUB: not implemented"; return }

func (h *ecdsaPrivateKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *ecdsaPrivateKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *ecdsaPrivateKey) Crv() (jwa.EllipticCurveAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.EllipticCurveAlgorithm), false
}

func (h *ecdsaPrivateKey) D() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *ecdsaPrivateKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPrivateKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *ecdsaPrivateKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPrivateKey) X() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *ecdsaPrivateKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *ecdsaPrivateKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *ecdsaPrivateKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *ecdsaPrivateKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *ecdsaPrivateKey) Y() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *ecdsaPrivateKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *ecdsaPrivateKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *ecdsaPrivateKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *ecdsaPrivateKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *ecdsaPrivateKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *ecdsaPrivateKey) cloneFrom(src *ecdsaPrivateKey) { _ = "STUB: not implemented"; return }

func (k *ecdsaPrivateKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *ecdsaPrivateKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *ecdsaPrivateKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *ecdsaPrivateKey) UnmarshalJSON(buf []byte) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// consume closing '}'

func (h *ecdsaPrivateKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *ecdsaPrivateKey) Keys() []string { _ = "STUB: not implemented"; return nil }

func init() {
	registry.Register(jwa.EC().String(), registry.Constructor{
		Public:  func() any { return newECDSAPublicKey() },
		Private: func() any { return newECDSAPrivateKey() },
	})
}
