// Code generated by internal/jwxcodegen/cmd/jwxcodegen (generate-readfile). DO NOT EDIT.

package jwk

import (
	"io/fs"
)

// ParseFS opens path on fsys and parses the contents.
func ParseFS(fsys fs.FS, path string, options ...ParseOption) (Set, error) {
	_ = "STUB: not implemented"
	return *new(Set), nil
}

// ReadFile opens path with os.Open and parses the contents. It accepts
// any path os.Open accepts, including absolute paths.
//
// Deprecated: prefer ParseFS, which works with any fs.FS (e.g. os.DirFS,
// embed.FS, testing/fstest). ReadFile is retained for v3 source compatibility.
func ReadFile(path string, options ...ParseOption) (Set, error) {
	_ = "STUB: not implemented"
	return *new(Set), nil
}
