// Code generated by tools/cmd/genjwk/main.go. DO NOT EDIT.

package jwk

import (
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk/internal/registry"
)

const (
	OKPCrvKey = "crv"
	OKPDKey   = "d"
	OKPXKey   = "x"
)

type OKPPublicKey interface {
	Key
	Crv() (jwa.EllipticCurveAlgorithm, bool)
	X() ([]byte, bool)
}

type okpPublicKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	crv                    *jwa.EllipticCurveAlgorithm
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	x                      []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ OKPPublicKey = &okpPublicKey{}
var _ Key = &okpPublicKey{}

func newOKPPublicKey() *okpPublicKey { _ = "STUB: not implemented"; return nil }

func (h *okpPublicKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *okpPublicKey) rlock() { _ = "STUB: not implemented"; return }

func (h *okpPublicKey) runlock() { _ = "STUB: not implemented"; return }

func (h *okpPublicKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *okpPublicKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *okpPublicKey) Crv() (jwa.EllipticCurveAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.EllipticCurveAlgorithm), false
}

func (h *okpPublicKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPublicKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *okpPublicKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPublicKey) X() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *okpPublicKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *okpPublicKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *okpPublicKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *okpPublicKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPublicKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *okpPublicKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *okpPublicKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *okpPublicKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *okpPublicKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *okpPublicKey) cloneFrom(src *okpPublicKey) { _ = "STUB: not implemented"; return }

func (k *okpPublicKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *okpPublicKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *okpPublicKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *okpPublicKey) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *okpPublicKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *okpPublicKey) Keys() []string { _ = "STUB: not implemented"; return nil }

type OKPPrivateKey interface {
	Key
	Crv() (jwa.EllipticCurveAlgorithm, bool)
	D() ([]byte, bool)
	X() ([]byte, bool)
}

type okpPrivateKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	crv                    *jwa.EllipticCurveAlgorithm
	d                      []byte
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	x                      []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ OKPPrivateKey = &okpPrivateKey{}
var _ Key = &okpPrivateKey{}

func newOKPPrivateKey() *okpPrivateKey { _ = "STUB: not implemented"; return nil }

func (h *okpPrivateKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *okpPrivateKey) rlock() { _ = "STUB: not implemented"; return }

func (h *okpPrivateKey) runlock() { _ = "STUB: not implemented"; return }

func (h *okpPrivateKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *okpPrivateKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *okpPrivateKey) Crv() (jwa.EllipticCurveAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.EllipticCurveAlgorithm), false
}

func (h *okpPrivateKey) D() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *okpPrivateKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPrivateKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *okpPrivateKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPrivateKey) X() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *okpPrivateKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *okpPrivateKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *okpPrivateKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *okpPrivateKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *okpPrivateKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *okpPrivateKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *okpPrivateKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *okpPrivateKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *okpPrivateKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *okpPrivateKey) cloneFrom(src *okpPrivateKey) { _ = "STUB: not implemented"; return }

func (k *okpPrivateKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *okpPrivateKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *okpPrivateKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *okpPrivateKey) UnmarshalJSON(buf []byte) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// consume closing '}'

func (h *okpPrivateKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *okpPrivateKey) Keys() []string { _ = "STUB: not implemented"; return nil }

func init() {
	registry.Register(jwa.OKP().String(), registry.Constructor{
		Public:  func() any { return newOKPPublicKey() },
		Private: func() any { return newOKPPrivateKey() },
	})
}
