package jwk

import (
	"crypto"
	"crypto/rsa"
	"math/big"
	"reflect"
	"sync/atomic"

	"github.com/lestrrat-go/jwx/v4/jwa"
)

func init() {
	panicOnRegistrationError(RegisterKeyExporter(KeyKind(jwa.RSA().String()), KeyExportFunc(rsaJWKToRaw)))
}

const minRSAModulusBits = 2048
const minRSAPublicExponent = 3

var rsaMinModulusBits = atomic.Int64{}
var rsaMinPublicExponent atomic.Pointer[big.Int]

func init() {
	rsaMinModulusBits.Store(minRSAModulusBits)
	setMinRSAPublicExponent(minRSAPublicExponent)
}

func setMinRSAPublicExponent(v int) { _ = "STUB: not implemented"; return }

func (k *rsaPrivateKey) Import(rawKey *rsa.PrivateKey) error { _ = "STUB: not implemented"; return nil }

/* I know, I'm being paranoid */

// dp, dq, qi are optional values

// public key part

func importRsaPublicKeyByteValues(rawKey *rsa.PublicKey) ([]byte, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

func (k *rsaPublicKey) Import(rawKey *rsa.PublicKey) error { _ = "STUB: not implemented"; return nil }

func validateRSAModulusAndExponent(n, e []byte) (*big.Int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// rsa.PublicKey.E is a Go int. Reject exponents that do not fit on the
// current platform (e.g. GOARCH=386). Without this guard, Int64()/int()
// silently truncates, causing the materialized key to disagree with the
// JSON bytes and breaking RFC 7638 thumbprint uniqueness.

func buildRSAPublicKey(key *rsa.PublicKey, n, e []byte) error {
	_ = "STUB: not implemented"
	return nil
}

var rsaConvertibleKeys = []reflect.Type{
	reflect.TypeFor[RSAPrivateKey](),
	reflect.TypeFor[RSAPublicKey](),
}

func rsaJWKToRaw(keyif Key, _ any) (any, error) {
	_ = "STUB: not implemented"
	// Fast path: built-in concrete types need no reflection
	return *new(any), nil
}

// already a concrete type, skip extractEmbeddedKey

//nolint:forcetypeassert // rlocker is unexported; only our concrete types implement it

// External implementation — use self-locking interface getters.

// note: do not use from sync.Pool

// note: do not use from sync.Pool

// note: do not use from sync.Pool

// note: do not use from sync.Pool

// This may look like a no-op, but it's required if we want to
// compare it against a key generated by rsa.GenerateKey

//nolint:forcetypeassert // rlocker is unexported; only our concrete types implement it

func makeRSAPublicKey(src Key) (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

// Iterate and copy everything except for the bits that should not be in the public key

func (k *rsaPrivateKey) PublicKey() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *rsaPublicKey) PublicKey() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

// Thumbprint returns the JWK thumbprint using the indicated
// hashing algorithm, according to RFC 7638
func (k *rsaPrivateKey) Thumbprint(hash crypto.Hash) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (k *rsaPublicKey) Thumbprint(hash crypto.Hash) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// trimLeadingZeroBytes strips leading zero bytes. RFC 7638 requires the
// minimal big-endian representation of n/e for canonical JSON.
func trimLeadingZeroBytes(b []byte) []byte { _ = "STUB: not implemented"; return nil }

func rsaThumbprint(hash crypto.Hash, n, e []byte) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func validateRSAKey(key interface {
	N() ([]byte, bool)
	E() ([]byte, bool)
}, checkPrivate bool) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *rsaPrivateKey) Validate() error { _ = "STUB: not implemented"; return nil }

func (k *rsaPublicKey) Validate() error { _ = "STUB: not implemented"; return nil }
