// Code generated by tools/cmd/genjwk/main.go. DO NOT EDIT.

package jwk

import (
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk/internal/registry"
)

const (
	RSADKey  = "d"
	RSADPKey = "dp"
	RSADQKey = "dq"
	RSAEKey  = "e"
	RSANKey  = "n"
	RSAPKey  = "p"
	RSAQIKey = "qi"
	RSAQKey  = "q"
)

type RSAPublicKey interface {
	Key
	E() ([]byte, bool)
	N() ([]byte, bool)
}

type rsaPublicKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	e                      []byte
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	n                      []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ RSAPublicKey = &rsaPublicKey{}
var _ Key = &rsaPublicKey{}

func newRSAPublicKey() *rsaPublicKey { _ = "STUB: not implemented"; return nil }

func (h *rsaPublicKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *rsaPublicKey) rlock() { _ = "STUB: not implemented"; return }

func (h *rsaPublicKey) runlock() { _ = "STUB: not implemented"; return }

func (h *rsaPublicKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *rsaPublicKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *rsaPublicKey) E() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPublicKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPublicKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *rsaPublicKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPublicKey) N() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPublicKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *rsaPublicKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *rsaPublicKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *rsaPublicKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPublicKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *rsaPublicKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *rsaPublicKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *rsaPublicKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *rsaPublicKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *rsaPublicKey) cloneFrom(src *rsaPublicKey) { _ = "STUB: not implemented"; return }

func (k *rsaPublicKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *rsaPublicKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *rsaPublicKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *rsaPublicKey) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *rsaPublicKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *rsaPublicKey) Keys() []string { _ = "STUB: not implemented"; return nil }

type RSAPrivateKey interface {
	Key
	D() ([]byte, bool)
	DP() ([]byte, bool)
	DQ() ([]byte, bool)
	E() ([]byte, bool)
	N() ([]byte, bool)
	P() ([]byte, bool)
	Q() ([]byte, bool)
	QI() ([]byte, bool)
}

type rsaPrivateKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	d                      []byte
	dp                     []byte
	dq                     []byte
	e                      []byte
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	n                      []byte
	p                      []byte
	q                      []byte
	qi                     []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ RSAPrivateKey = &rsaPrivateKey{}
var _ Key = &rsaPrivateKey{}

func newRSAPrivateKey() *rsaPrivateKey { _ = "STUB: not implemented"; return nil }

func (h *rsaPrivateKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *rsaPrivateKey) rlock() { _ = "STUB: not implemented"; return }

func (h *rsaPrivateKey) runlock() { _ = "STUB: not implemented"; return }

func (h *rsaPrivateKey) IsPrivate() bool { _ = "STUB: not implemented"; return false }

func (h *rsaPrivateKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *rsaPrivateKey) D() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) DP() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) DQ() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) E() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPrivateKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *rsaPrivateKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPrivateKey) N() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) P() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) Q() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) QI() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *rsaPrivateKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *rsaPrivateKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *rsaPrivateKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *rsaPrivateKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *rsaPrivateKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *rsaPrivateKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *rsaPrivateKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *rsaPrivateKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *rsaPrivateKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *rsaPrivateKey) cloneFrom(src *rsaPrivateKey) { _ = "STUB: not implemented"; return }

func (k *rsaPrivateKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *rsaPrivateKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *rsaPrivateKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *rsaPrivateKey) UnmarshalJSON(buf []byte) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// consume closing '}'

func (h *rsaPrivateKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *rsaPrivateKey) Keys() []string { _ = "STUB: not implemented"; return nil }

func init() {
	registry.Register(jwa.RSA().String(), registry.Constructor{
		Public:  func() any { return newRSAPublicKey() },
		Private: func() any { return newRSAPrivateKey() },
	})
}
