// Code generated by tools/cmd/genjwk/main.go. DO NOT EDIT.

package jwk

import (
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk/internal/registry"
)

const (
	SymmetricOctetsKey = "k"
)

type SymmetricKey interface {
	Key
	Octets() ([]byte, bool)
}

type symmetricKey struct {
	algorithm              *jwa.KeyAlgorithm // https://tools.ietf.org/html/rfc7517#section-4.4
	keyID                  *string           // https://tools.ietf.org/html/rfc7515#section-4.1.4
	keyOps                 *KeyOperationList // https://tools.ietf.org/html/rfc7517#section-4.3
	keyUsage               *string           // https://tools.ietf.org/html/rfc7517#section-4.2
	octets                 []byte
	x509CertChain          *cert.Chain // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string     // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string     // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string     // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     json.DecodeCtx
}

var _ SymmetricKey = &symmetricKey{}
var _ Key = &symmetricKey{}

func newSymmetricKey() *symmetricKey { _ = "STUB: not implemented"; return nil }

func (h *symmetricKey) KeyType() jwa.KeyType { _ = "STUB: not implemented"; return *new(jwa.KeyType) }

func (h *symmetricKey) rlock() { _ = "STUB: not implemented"; return }

func (h *symmetricKey) runlock() { _ = "STUB: not implemented"; return }

func (h *symmetricKey) Algorithm() (jwa.KeyAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyAlgorithm), false
}

func (h *symmetricKey) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *symmetricKey) KeyOps() (KeyOperationList, bool) {
	_ = "STUB: not implemented"
	return *new(KeyOperationList), false
}

func (h *symmetricKey) KeyUsage() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *symmetricKey) Octets() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *symmetricKey) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *symmetricKey) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *symmetricKey) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *symmetricKey) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *symmetricKey) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *symmetricKey) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *symmetricKey) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *symmetricKey) setNoLock(name string, value any) error {
	_ = "STUB: not implemented"
	return nil
}

func (k *symmetricKey) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (dst *symmetricKey) cloneFrom(src *symmetricKey) { _ = "STUB: not implemented"; return }

func (k *symmetricKey) Clone() (Key, error) { _ = "STUB: not implemented"; return *new(Key), nil }

func (k *symmetricKey) DecodeCtx() json.DecodeCtx {
	_ = "STUB: not implemented"
	return *new(json.DecodeCtx)
}

func (k *symmetricKey) SetDecodeCtx(dc json.DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *symmetricKey) UnmarshalJSON(buf []byte) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// consume closing '}'

func (h *symmetricKey) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (h *symmetricKey) Keys() []string { _ = "STUB: not implemented"; return nil }

func init() {
	registry.Register(jwa.OctetSeq().String(), registry.Constructor{
		Private: func() any { return newSymmetricKey() },
	})
}
