// Code generated by tools/cmd/genoptions/main.go. DO NOT EDIT.

package jwt

import (
	"context"
	"net/http"
	"time"

	"github.com/lestrrat-go/jwx/v4/jwe"
	"github.com/lestrrat-go/jwx/v4/jws"
	"github.com/lestrrat-go/option/v3"
)

type Option = option.Interface

// EncryptOption describes an Option that can be passed to (jwt.Serializer).Encrypt
type EncryptOption interface {
	Option
	encryptOption()
}

type encryptOption struct {
	Option
}

func (*encryptOption) encryptOption() {
	_ = "STUB: not implemented"

	// GlobalOption describes an Option that can be passed to `Settings()`.
	return
}

type GlobalOption interface {
	Option
	globalOption()
}

type globalOption struct {
	Option
}

func (*globalOption) globalOption() {
	_ = "STUB: not implemented"

	// GlobalParseOption describes an Option that can be passed to `jwt.Settings()`
	// and `jwt.Parse()`.
	return
}

type GlobalParseOption interface {
	Option
	globalOption()
	parseOption()
}

type globalParseOption struct {
	Option
}

func (*globalParseOption) globalOption() { _ = "STUB: not implemented"; return }

func (*globalParseOption) parseOption() {
	_ = "STUB: not implemented"

	// GlobalValidateOption describes an Option that can be passed to `jwt.Settings()` and `jwt.Validate()`
	return
}

type GlobalValidateOption interface {
	Option
	globalOption()
	parseOption()
	validateOption()
}

type globalValidateOption struct {
	Option
}

func (*globalValidateOption) globalOption() { _ = "STUB: not implemented"; return }

func (*globalValidateOption) parseOption() { _ = "STUB: not implemented"; return }

func (*globalValidateOption) validateOption() {
	_ = "STUB: not implemented"

	// ParseOption describes an Option that can be passed to `jwt.Parse()`.
	return
}

type ParseOption interface {
	Option
	parseOption()
}

type parseOption struct {
	Option
}

func (*parseOption) parseOption() {
	_ = "STUB: not implemented"

	// SignEncryptParseOption describes an Option that can be passed to both `jwt.Sign()` or
	// `jwt.Parse()`
	return
}

type SignEncryptParseOption interface {
	Option
	parseOption()
	encryptOption()
	signOption()
}

type signEncryptParseOption struct {
	Option
}

func (*signEncryptParseOption) parseOption() { _ = "STUB: not implemented"; return }

func (*signEncryptParseOption) encryptOption() { _ = "STUB: not implemented"; return }

func (*signEncryptParseOption) signOption() {
	_ = "STUB: not implemented"

	// SignOption describes an Option that can be passed to `jwt.Sign()` or
	// (jwt.Serializer).Sign
	return
}

type SignOption interface {
	Option
	signOption()
}

type signOption struct {
	Option
}

func (*signOption) signOption() {
	_ = "STUB: not implemented"

	// SignParseOption describes an Option that can be passed to both `jwt.Sign()` or
	// `jwt.Parse()`
	return
}

type SignParseOption interface {
	Option
	signOption()
	parseOption()
}

type signParseOption struct {
	Option
}

func (*signParseOption) signOption() { _ = "STUB: not implemented"; return }

func (*signParseOption) parseOption() {
	_ = "STUB: not implemented"

	// ValidateOption describes an Option that can be passed to Validate().
	// ValidateOption also implements ParseOption, therefore it may be
	// safely passed to `Parse()`
	return
}

type ValidateOption interface {
	Option
	parseOption()
	validateOption()
}

type validateOption struct {
	Option
}

func (*validateOption) parseOption() { _ = "STUB: not implemented"; return }

func (*validateOption) validateOption() { _ = "STUB: not implemented"; return }

type identAcceptableSkew struct{}
type identBase64Encoder struct{}
type identClock struct{}
type identCollectErrors struct{}
type identContext struct{}
type identCookie struct{}
type identCookieKey struct{}
type identEncryptOption struct{}
type identFlattenAudience struct{}
type identFormKey struct{}
type identHeaderKey struct{}
type identKeyProvider struct{}
type identNumericDateFormatPrecision struct{}
type identNumericDateParsePedantic struct{}
type identNumericDateParsePrecision struct{}
type identPedantic struct{}
type identResetValidators struct{}
type identSignOption struct{}
type identStrictBase64Encoding struct{}
type identStrictStringClaims struct{}
type identToken struct{}
type identTruncation struct{}
type identValidate struct{}
type identValidator struct{}
type identVerify struct{}

func (identAcceptableSkew) String() string { _ = "STUB: not implemented"; return "" }

func (identBase64Encoder) String() string { _ = "STUB: not implemented"; return "" }

func (identClock) String() string { _ = "STUB: not implemented"; return "" }

func (identCollectErrors) String() string { _ = "STUB: not implemented"; return "" }

func (identContext) String() string { _ = "STUB: not implemented"; return "" }

func (identCookie) String() string { _ = "STUB: not implemented"; return "" }

func (identCookieKey) String() string { _ = "STUB: not implemented"; return "" }

func (identEncryptOption) String() string { _ = "STUB: not implemented"; return "" }

func (identFlattenAudience) String() string { _ = "STUB: not implemented"; return "" }

func (identFormKey) String() string { _ = "STUB: not implemented"; return "" }

func (identHeaderKey) String() string { _ = "STUB: not implemented"; return "" }

func (identKeyProvider) String() string { _ = "STUB: not implemented"; return "" }

func (identNumericDateFormatPrecision) String() string { _ = "STUB: not implemented"; return "" }

func (identNumericDateParsePedantic) String() string { _ = "STUB: not implemented"; return "" }

func (identNumericDateParsePrecision) String() string { _ = "STUB: not implemented"; return "" }

func (identPedantic) String() string { _ = "STUB: not implemented"; return "" }

func (identResetValidators) String() string { _ = "STUB: not implemented"; return "" }

func (identSignOption) String() string { _ = "STUB: not implemented"; return "" }

func (identStrictBase64Encoding) String() string { _ = "STUB: not implemented"; return "" }

func (identStrictStringClaims) String() string { _ = "STUB: not implemented"; return "" }

func (identToken) String() string { _ = "STUB: not implemented"; return "" }

func (identTruncation) String() string { _ = "STUB: not implemented"; return "" }

func (identValidate) String() string { _ = "STUB: not implemented"; return "" }

func (identValidator) String() string { _ = "STUB: not implemented"; return "" }

func (identVerify) String() string { _ = "STUB: not implemented"; return "" }

// WithAcceptableSkew specifies the duration in which exp, iat and nbf
// claims may differ by. This value should be positive
func WithAcceptableSkew(v time.Duration) ValidateOption {
	_ = "STUB: not implemented"
	return *new(ValidateOption)
}

// WithBase64Encoder specifies the base64 encoder to use for signing
// tokens and verifying JWS signatures.
func WithBase64Encoder(v jws.Base64Encoder) SignParseOption {
	_ = "STUB: not implemented"
	return *new(SignParseOption)
}

// WithClock specifies the `Clock` to be used when verifying
// exp, iat and nbf claims.
func WithClock(v Clock) ValidateOption { _ = "STUB: not implemented"; return *new(ValidateOption) }

// WithCollectErrors specifies that all validators should be run and
// all errors collected, instead of returning on the first failure.
// The resulting error wraps all individual errors via errors.Join,
// so each cause can be inspected using errors.Is or errors.AsType.
//
// By default, jwt.Validate returns on the first validation error,
// matching v3 behavior. Use WithCollectErrors(true) to gather all
// validation errors in a single call.
//
// Configuration-level errors short-circuit regardless of this
// option: a negative WithAcceptableSkew, an unsupported claim name
// passed to WithMaxDelta/WithMinDelta, or a WithResetValidators(true)
// call with no WithValidator() in the same Validate invocation each
// abort the call with a single error. Only validator outcomes
// (TokenExpiredError, InvalidAudienceError, caller-supplied
// Validator return values, and similar) are collected.
func WithCollectErrors(v bool) ValidateOption {
	_ = "STUB: not implemented"
	return *new(ValidateOption)
}

// WithContext allows you to specify a context.Context object to be used
// with `jwt.Validate()` option.
//
// Please be aware that in the next major release of this library,
// `jwt.Validate()`'s signature will change to include an explicit
// `context.Context` object.
func WithContext(v context.Context) ValidateOption {
	_ = "STUB: not implemented"
	return *new(ValidateOption)
}

// WithCookie is used to specify a variable to store the cookie used when `jwt.ParseCookie()`
// is called. This allows you to inspect the cookie for additional information after a successful
// parsing of the JWT token stored in the cookie.
//
// While the type system allows this option to be passed to `jwt.Parse()` directly,
// doing so will have no effect. Only use it for HTTP request parsing functions
func WithCookie(v **http.Cookie) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithCookieKey is used to specify cookie keys to search for tokens.
//
// While the type system allows this option to be passed to `jwt.Parse()` directly,
// doing so will have no effect. Only use it for HTTP request parsing functions
func WithCookieKey(v string) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithEncryptOption provides an escape hatch for cases where extra options to
// `(jws.Serializer).Encrypt()` must be specified when using `jwt.Sign()`. Normally you do not
// need to use this.
func WithEncryptOption(v jwe.EncryptOption) EncryptOption {
	_ = "STUB: not implemented"
	return *new(EncryptOption)
}

// WithFlattenAudience specifies the the `jwt.FlattenAudience` option on
// every token defaults to enabled. You can still disable this on a per-object
// basis using the `jwt.Options().Disable(jwt.FlattenAudience)` method call.
//
// See the documentation for `jwt.TokenOptionSet`, `(jwt.Token).Options`, and
// `jwt.FlattenAudience` for more details
func WithFlattenAudience(v bool) GlobalOption { _ = "STUB: not implemented"; return *new(GlobalOption) }

// WithFormKey is used to specify header keys to search for tokens.
//
// While the type system allows this option to be passed to jwt.Parse() directly,
// doing so will have no effect. Only use it for HTTP request parsing functions
func WithFormKey(v string) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithHeaderKey is used to specify header keys to search for tokens.
//
// While the type system allows this option to be passed to `jwt.Parse()` directly,
// doing so will have no effect. Only use it for HTTP request parsing functions
func WithHeaderKey(v string) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithKeyProvider allows users to specify an object to provide keys to
// sign/verify tokens using arbitrary code. Please read the documentation
// for `jws.KeyProvider` in the `jws` package for details on how this works.
func WithKeyProvider(v jws.KeyProvider) ParseOption {
	_ = "STUB: not implemented"
	return *new(ParseOption)
}

// WithNumericDateFormatPrecision sets the precision up to which the
// library uses to format fractional dates found in the numeric date
// fields. Default is 0 (second, no fractions), max is 9 (nanosecond)
func WithNumericDateFormatPrecision(v int) GlobalOption {
	_ = "STUB: not implemented"
	return *new(GlobalOption)
}

// WithNumericDateParsePedantic specifies if the parser should behave
// in a pedantic manner when parsing numeric dates. Normally this library
// attempts to interpret timestamps as a numeric value representing
// number of seconds (with an optional fractional part), but if that fails
// it tries to parse using a RFC3339 parser. This allows us to parse
// payloads from non-conforming servers.
//
// However, when you set WithNumericDateParePedantic to `true`, the
// RFC3339 parser is not tried, and we expect a numeric value strictly
func WithNumericDateParsePedantic(v bool) GlobalOption {
	_ = "STUB: not implemented"
	return *new(GlobalOption)
}

// WithNumericDateParsePrecision sets the precision up to which the
// library uses to parse fractional dates found in the numeric date
// fields. Default is 0 (second, no fractions), max is 9 (nanosecond)
func WithNumericDateParsePrecision(v int) GlobalOption {
	_ = "STUB: not implemented"
	return *new(GlobalOption)
}

// WithPedantic enables pedantic mode for parsing JWTs. Currently this only
// applies to checking for the correct `typ` and/or `cty` when necessary.
func WithPedantic(v bool) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithResetValidators specifies that the default validators should be
// reset before applying the custom validators. By default `jwt.Validate()`
// checks for the validity of JWT by checking `exp`, `nbf`, and `iat`, even
// when you specify more validators through other options.
//
// You SHOULD NOT use this option unless you know exactly what you are doing,
// as this will pose significant security issues when used incorrectly.
//
// Using this option with the value `true` will remove all default checks,
// and will expect you to specify validators as options. This is useful when you
// want to skip the default validators and only use specific validators, such as
// for https://openid.net/specs/openid-connect-rpinitiated-1_0.html, where
// the token could be accepted even if the token is expired.
//
// If you set this option to true and you do not specify any validators,
// `jwt.Validate()` will return an error.
//
// The default value is `false` (`iat`, `exp`, and `nbf` are automatically checked).
func WithResetValidators(v bool) ValidateOption {
	_ = "STUB: not implemented"
	return *new(ValidateOption)
}

// WithSignOption provides an escape hatch for cases where extra options to
// `jws.Sign()` must be specified when using `jwt.Sign()`. Normally you do not
// need to use this.
func WithSignOption(v jws.SignOption) SignOption {
	_ = "STUB: not implemented"
	return *new(SignOption)
}

// WithStrictBase64Encoding controls whether base64 decoding during
// JWT parsing uses strict base64url encoding (RFC 4648 §5, no padding)
// or auto-detects the encoding variant.
//
// By default this is true: the parser uses base64.RawURLEncoding directly,
// which is faster and matches RFC 7515. Set to false to enable auto-detection
// for compatibility with non-conformant providers that may use padded or
// standard base64 encoding.
//
// Caveat: strict decoding is applied on the fast path only. Messages
// whose protected header carries a "crit" list bypass the fast path
// (`jws.VerifyCompactFast` refuses them, see its godoc) and are
// re-verified through `jws.Verify`, which uses the lenient
// auto-detecting base64 decoder. As a result, "strict by default"
// applies only when the message has no "crit" header.
func WithStrictBase64Encoding(v bool) ParseOption {
	_ = "STUB: not implemented"
	return *new(ParseOption)
}

// WithStrictStringClaims controls whether JSON null values for string
// claims (such as "iss", "sub", "jti") cause a parse error. By default,
// null is silently accepted as an empty string (matching Go's standard
// JSON decoding behavior). When set to true, null values are rejected
// per the RFC type definitions (e.g. StringOrURI).
//
// This option only affects JWT claims. JWK, JWE, and JWS fields are
// not subject to this check and will always accept null as an empty string.
func WithStrictStringClaims(v bool) ParseOption {
	_ = "STUB: not implemented"
	return *new(ParseOption)
}

// WithToken specifies the token instance in which the resulting JWT is stored
// when parsing JWT tokens
func WithToken(v Token) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithTruncation specifies the amount that should be used when
// truncating time values used during time-based validation routines,
// and by default this is disabled.
//
// In v2 of this library, time values were truncated down to second accuracy, i.e.
// 1.0000001 seconds is truncated to 1 second. To restore this behavior, set
// this value to `time.Second`
//
// Since v3, this option can be passed to `jwt.Settings()` to set the truncation
// value globally, as well as per invocation of `jwt.Validate()`
func WithTruncation(v time.Duration) GlobalValidateOption {
	_ = "STUB: not implemented"
	return *new(GlobalValidateOption)
}

// WithValidate is passed to `Parse()` method to denote that the
// validation of the JWT token should be performed (or not) after
// a successful parsing of the incoming payload.
//
// This option is enabled by default.
//
// If you would like disable validation,
// you must use `jwt.WithValidate(false)` or use `jwt.ParseInsecure()`
func WithValidate(v bool) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }

// WithValidator validates the token with the given Validator.
//
// For example, in order to validate tokens that are only valid during August, you would write
//
//	validator := jwt.ValidatorFunc(func(_ context.Context, t jwt.Token) error {
//		if time.Now().Month() != 8 {
//			return fmt.Errorf(`tokens are only valid during August!`)
//		}
//		return nil
//	})
//	err := jwt.Validate(token, jwt.WithValidator(validator))
func WithValidator(v Validator) ValidateOption {
	_ = "STUB: not implemented"
	return *new(ValidateOption)
}

// WithVerify is passed to `Parse()` method to denote that the
// signature verification should be performed after a successful
// deserialization of the incoming payload.
//
// This option is enabled by default.
//
// If you do not provide any verification key sources, `jwt.Parse()`
// would return an error.
//
// If you would like to only parse the JWT payload and not verify it,
// you must use `jwt.WithVerify(false)` or use `jwt.ParseInsecure()`
func WithVerify(v bool) ParseOption { _ = "STUB: not implemented"; return *new(ParseOption) }
