// Code generated by tools/cmd/genjwt/main.go. DO NOT EDIT.

package jwt

import (
	"iter"
	"sync"
	"time"

	"github.com/lestrrat-go/jwx/v4/jwt/internal/types"
)

const (
	AudienceKey   = "aud"
	ExpirationKey = "exp"
	IssuedAtKey   = "iat"
	IssuerKey     = "iss"
	JwtIDKey      = "jti"
	NotBeforeKey  = "nbf"
	SubjectKey    = "sub"
)

// Token represents a generic JWT token.
// which are type-aware (to an extent). Other claims may be accessed via the `Get`/`Set`
// methods but their types are not taken into consideration at all. If you have non-standard
// claims that you must frequently access, consider creating accessors functions
// like the following
//
// func SetFoo(tok jwt.Token) error
// func GetFoo(tok jwt.Token) (*Customtyp, error)
//
// Embedding jwt.Token into another struct is not recommended, because
// jwt.Token needs to handle private claims, and this really does not
// work well when it is embedded in other structure
type Token interface {
	// Audience returns the value for "aud" field of the token
	Audience() ([]string, bool)

	// Expiration returns the value for "exp" field of the token
	Expiration() (time.Time, bool)

	// IssuedAt returns the value for "iat" field of the token
	IssuedAt() (time.Time, bool)

	// Issuer returns the value for "iss" field of the token
	Issuer() (string, bool)

	// JwtID returns the value for "jti" field of the token
	JwtID() (string, bool)

	// NotBefore returns the value for "nbf" field of the token
	NotBefore() (time.Time, bool)

	// Subject returns the value for "sub" field of the token
	Subject() (string, bool)

	// Field returns the value of a claim by name, along with a boolean indicating
	// whether the claim was found. For standard claims, you can also use the
	// corresponding getter method, such as `Issuer()`, `Subject()`, etc.
	// For type-safe access to claims, use the `jwt.Get[T]()` generic accessor.
	Field(string) (any, bool)

	// Set assigns a value to the corresponding field in the token. Some
	// pre-defined fields such as `nbf`, `iat`, `iss` need their values to
	// be of a specific type. See the other getter methods in this interface
	// for the types of each of these fields
	Set(string, any) error

	// Has returns true if the specified claim has a value, even if
	// the value is empty-ish (e.g. 0, false, "")  as long as it has been
	// explicitly set.
	Has(string) bool
	Remove(string) error

	// Options returns the per-token options associated with this token.
	// The options set value will be copied when the token is cloned via `Clone()`
	// but it will not survive when the token goes through marshaling/unmarshaling
	// such as `json.Marshal` and `json.Unmarshal`
	Options() *TokenOptionSet
	Clone() (Token, error)
	Keys() []string
	// Claims returns an iterator over all claims (standard and private) in the token.
	Claims() iter.Seq2[string, any]
}
type stdToken struct {
	mu            sync.RWMutex
	dc            DecodeCtx          // per-object context for decoding
	options       TokenOptionSet     // per-object option
	audience      types.StringList   // https://tools.ietf.org/html/rfc7519#section-4.1.3
	expiration    *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.4
	issuedAt      *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.6
	issuer        *string            // https://tools.ietf.org/html/rfc7519#section-4.1.1
	jwtID         *string            // https://tools.ietf.org/html/rfc7519#section-4.1.7
	notBefore     *types.NumericDate // https://tools.ietf.org/html/rfc7519#section-4.1.5
	subject       *string            // https://tools.ietf.org/html/rfc7519#section-4.1.2
	privateClaims map[string]any
}

// New creates a standard token, with minimal knowledge of
// possible claims. Standard claims include"aud", "exp", "iat", "iss", "jti", "nbf" and "sub".
// Convenience accessors are provided for these standard claims
func New() Token { _ = "STUB: not implemented"; return *new(Token) }

func (t *stdToken) Options() *TokenOptionSet { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (t *stdToken) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (t *stdToken) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) DecodeCtx() DecodeCtx { _ = "STUB: not implemented"; return *new(DecodeCtx) }

func (t *stdToken) SetDecodeCtx(v DecodeCtx) { _ = "STUB: not implemented"; return }

func (t *stdToken) setNoLock(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Audience() ([]string, bool) { _ = "STUB: not implemented"; return nil, false }

func (t *stdToken) Expiration() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) IssuedAt() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) Issuer() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) JwtID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (t *stdToken) NotBefore() (time.Time, bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

func (t *stdToken) Subject() (string, bool) { _ = "STUB: not implemented"; return "", false }

// PrivateClaims returns the underlying map of non-standard claims held by
// the token. The returned map is the live map used by the token, not a copy:
// callers must not mutate it, and must not read from it concurrently with
// Set/Remove or with unmarshaling on the same token. If you need a stable
// snapshot for concurrent use, copy the map (for example via maps.Clone)
// before iterating.
//
// To obtain a fresh token containing only the non-standard claims, use the
// jwxfilter companion module: jwtfilter.Standard().Reject(token) from
// github.com/jwx-go/jwxfilter/v4/jwtfilter (or openidfilter.Standard().Reject
// for openid.Token).
func (t *stdToken) PrivateClaims() map[string]any { _ = "STUB: not implemented"; return nil }

func (t *stdToken) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (t *stdToken) Keys() []string { _ = "STUB: not implemented"; return nil }

func (t *stdToken) Claims() iter.Seq2[string, any] { _ = "STUB: not implemented"; return nil }

func (dst *stdToken) cloneFrom(src *stdToken) { _ = "STUB: not implemented"; return }

type claimPair struct {
	Name  string
	Value any
}

var claimPairPool = sync.Pool{
	New: func() any {
		return make([]claimPair, 0, 7)
	},
}

func getClaimPairList() []claimPair { _ = "STUB: not implemented"; return nil }

func putClaimPairList(list []claimPair) { _ = "STUB: not implemented"; return }

func (t *stdToken) makePairs() []claimPair { _ = "STUB: not implemented"; return nil }

func (t *stdToken) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
