// Code generated by "stringer -type=TokenOption -output=token_options_gen.go"; DO NOT EDIT.

package jwt

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _TokenOption_name = "FlattenAudienceMaxPerTokenOption"

var _TokenOption_index = [...]uint8{0, 15, 32}

func (i TokenOption) String() string { _ = "STUB: not implemented"; return "" }
