// Code generated by tools/cmd/genheaders/main.go. DO NOT EDIT.

package jws

import (
	"bytes"
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk"
)

const (
	AlgorithmKey              = "alg"
	B64Key                    = "b64"
	ContentTypeKey            = "cty"
	CriticalKey               = "crit"
	JWKKey                    = "jwk"
	JWKSetURLKey              = "jku"
	KeyIDKey                  = "kid"
	TypeKey                   = "typ"
	X509CertChainKey          = "x5c"
	X509CertThumbprintKey     = "x5t"
	X509CertThumbprintS256Key = "x5t#S256"
	X509URLKey                = "x5u"
)

// Headers describe a standard JWS Header set. It is part of the JWS message
// and is used to represet both Public or Protected headers, which in turn
// can be found in each Signature object. If you are not sure how this works,
// it is strongly recommended that you read RFC7515, especially the section
// that describes the full JSON serialization format of JWS messages.
//
// In most cases, you likely want to use the protected headers, as this is part of the signed content.
type Headers interface {
	Algorithm() (jwa.SignatureAlgorithm, bool)
	B64() (bool, bool)
	ContentType() (string, bool)
	Critical() ([]string, bool)
	JWK() (jwk.Key, bool)
	JWKSetURL() (string, bool)
	KeyID() (string, bool)
	Type() (string, bool)
	X509CertChain() (*cert.Chain, bool)
	X509CertThumbprint() (string, bool)
	X509CertThumbprintS256() (string, bool)
	X509URL() (string, bool)
	Copy(Headers) error
	Merge(Headers) (Headers, error)
	Clone() (Headers, error)
	// Field returns the value of a header field by name, along with a boolean indicating
	// whether the field was found. For type-safe access, use the `jws.Get[T]()` generic accessor.
	Field(string) (any, bool)
	Set(string, any) error
	Remove(string) error
	// Has returns true if the specified header has a value, even if
	// the value is empty-ish (e.g. 0, false, "")  as long as it has been
	// explicitly set.
	Has(string) bool
	Keys() []string
}

// stdHeaderNames is a list of all standard header names defined in the JWS specification.
var stdHeaderNames = []string{AlgorithmKey, B64Key, ContentTypeKey, CriticalKey, JWKKey, JWKSetURLKey, KeyIDKey, TypeKey, X509CertChainKey, X509CertThumbprintKey, X509CertThumbprintS256Key, X509URLKey}

type stdHeaders struct {
	algorithm              *jwa.SignatureAlgorithm // https://tools.ietf.org/html/rfc7515#section-4.1.1
	b64                    *bool                   // https://tools.ietf.org/html/rfc7797#section-3
	contentType            *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.10
	critical               []string                // https://tools.ietf.org/html/rfc7515#section-4.1.11
	jwk                    jwk.Key                 // https://tools.ietf.org/html/rfc7515#section-4.1.3
	jwkSetURL              *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.2
	keyID                  *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.4
	typ                    *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.9
	x509CertChain          *cert.Chain             // https://tools.ietf.org/html/rfc7515#section-4.1.6
	x509CertThumbprint     *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.7
	x509CertThumbprintS256 *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.8
	x509URL                *string                 // https://tools.ietf.org/html/rfc7515#section-4.1.5
	privateParams          map[string]any
	mu                     sync.RWMutex
	dc                     DecodeCtx
	raw                    []byte // stores the raw version of the header so it can be used later
}

func NewHeaders() Headers { _ = "STUB: not implemented"; return *new(Headers) }

func (h *stdHeaders) Algorithm() (jwa.SignatureAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.SignatureAlgorithm), false
}

func (h *stdHeaders) B64() (bool, bool) { _ = "STUB: not implemented"; return false, false }

func (h *stdHeaders) ContentType() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) Critical() ([]string, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *stdHeaders) JWK() (jwk.Key, bool) { _ = "STUB: not implemented"; return *new(jwk.Key), false }

func (h *stdHeaders) JWKSetURL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) Type() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *stdHeaders) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *stdHeaders) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *stdHeaders) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) clear() { _ = "STUB: not implemented"; return }

func (h *stdHeaders) isZero() bool { _ = "STUB: not implemented"; return false }

func (h *stdHeaders) DecodeCtx() DecodeCtx { _ = "STUB: not implemented"; return *new(DecodeCtx) }

func (h *stdHeaders) SetDecodeCtx(dc DecodeCtx) { _ = "STUB: not implemented"; return }

func (h *stdHeaders) rawBuffer() []byte { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) PrivateParams() map[string]any { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *stdHeaders) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *stdHeaders) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) setNoLock(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *stdHeaders) Keys() []string { _ = "STUB: not implemented"; return nil }

func (dst *stdHeaders) cloneFrom(src *stdHeaders) { _ = "STUB: not implemented"; return }

type fieldPair struct {
	Name  string
	Value any
}

type fieldPairList struct {
	pairs []fieldPair
}

var fieldPairPool = sync.Pool{
	New: func() any {
		return &fieldPairList{pairs: make([]fieldPair, 0, 16)}
	},
}

func getFieldPairList() *fieldPairList {
	_ = "STUB: not implemented"
	//nolint:forcetypeassert
	return nil
}

func putFieldPairList(l *fieldPairList) { _ = "STUB: not implemented"; return }

func fieldPairLess(a, b fieldPair) int { _ = "STUB: not implemented"; return 0 }

func writeQuotedKey(buf *bytes.Buffer, key string) { _ = "STUB: not implemented"; return }

func (h *stdHeaders) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
