// Code generated by tools/cmd/genheaders/main.go. DO NOT EDIT.

package jwe

import (
	"bytes"
	"sync"

	"github.com/lestrrat-go/jwx/v4/cert"
	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/lestrrat-go/jwx/v4/jwk"
)

const (
	AgreementPartyUInfoKey    = "apu"
	AgreementPartyVInfoKey    = "apv"
	AlgorithmKey              = "alg"
	CompressionKey            = "zip"
	ContentEncryptionKey      = "enc"
	ContentTypeKey            = "cty"
	CriticalKey               = "crit"
	EncapsulatedKeyKey        = "ek"
	EphemeralPublicKeyKey     = "epk"
	JWKKey                    = "jwk"
	JWKSetURLKey              = "jku"
	KeyIDKey                  = "kid"
	PSKIDKey                  = "psk_id"
	TypeKey                   = "typ"
	X509CertChainKey          = "x5c"
	X509CertThumbprintKey     = "x5t"
	X509CertThumbprintS256Key = "x5t#S256"
	X509URLKey                = "x5u"
)

// Headers describe a standard JWE Header set. It is part of the JWE message
// and is used to represent both Protected and Unprotected headers,
// which in turn can be found in each Recipient object.
// If you are not sure how this works, it is strongly recommended that
// you read RFC7516, especially the section
// that describes the full JSON serialization format of JWE messages.
//
// In most cases, you likely want to use the protected headers, as this is the part of the encrypted content
type Headers interface {
	AgreementPartyUInfo() ([]byte, bool)
	AgreementPartyVInfo() ([]byte, bool)
	Algorithm() (jwa.KeyEncryptionAlgorithm, bool)
	Compression() (jwa.CompressionAlgorithm, bool)
	ContentEncryption() (jwa.ContentEncryptionAlgorithm, bool)
	ContentType() (string, bool)
	Critical() ([]string, bool)
	EncapsulatedKey() ([]byte, bool)
	EphemeralPublicKey() (jwk.Key, bool)
	JWK() (jwk.Key, bool)
	JWKSetURL() (string, bool)
	KeyID() (string, bool)
	PSKID() ([]byte, bool)
	Type() (string, bool)
	X509CertChain() (*cert.Chain, bool)
	X509CertThumbprint() (string, bool)
	X509CertThumbprintS256() (string, bool)
	X509URL() (string, bool)
	// Field returns the value of a header field by name, along with a boolean indicating
	// whether the field was found. For type-safe access, use the `jwe.Get[T]()` generic accessor.
	Field(string) (any, bool)
	Set(string, any) error
	Remove(string) error
	// Has returns true if the specified header has a value, even if
	// the value is empty-ish (e.g. 0, false, "")  as long as it has been
	// explicitly set.
	Has(string) bool
	Encode() ([]byte, error)
	Decode([]byte) error
	Clone() (Headers, error)
	Copy(Headers) error
	Merge(Headers) (Headers, error)

	// Keys returns a list of the keys contained in this header.
	Keys() []string
}

// stdHeaderNames is a list of all standard header names defined in the JWE specification.
var stdHeaderNames = []string{AgreementPartyUInfoKey, AgreementPartyVInfoKey, AlgorithmKey, CompressionKey, ContentEncryptionKey, ContentTypeKey, CriticalKey, EncapsulatedKeyKey, EphemeralPublicKeyKey, JWKKey, JWKSetURLKey, KeyIDKey, PSKIDKey, TypeKey, X509CertChainKey, X509CertThumbprintKey, X509CertThumbprintS256Key, X509URLKey}

type stdHeaders struct {
	agreementPartyUInfo    []byte
	agreementPartyVInfo    []byte
	algorithm              *jwa.KeyEncryptionAlgorithm
	compression            *jwa.CompressionAlgorithm
	contentEncryption      *jwa.ContentEncryptionAlgorithm
	contentType            *string
	critical               []string
	encapsulatedKey        []byte
	ephemeralPublicKey     jwk.Key
	jwk                    jwk.Key
	jwkSetURL              *string
	keyID                  *string
	pskID                  []byte
	typ                    *string
	x509CertChain          *cert.Chain
	x509CertThumbprint     *string
	x509CertThumbprintS256 *string
	x509URL                *string
	privateParams          map[string]any
	mu                     sync.RWMutex
}

func NewHeaders() Headers { _ = "STUB: not implemented"; return *new(Headers) }

func (h *stdHeaders) AgreementPartyUInfo() ([]byte, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *stdHeaders) AgreementPartyVInfo() ([]byte, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *stdHeaders) Algorithm() (jwa.KeyEncryptionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.KeyEncryptionAlgorithm), false
}

func (h *stdHeaders) Compression() (jwa.CompressionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.CompressionAlgorithm), false
}

func (h *stdHeaders) ContentEncryption() (jwa.ContentEncryptionAlgorithm, bool) {
	_ = "STUB: not implemented"
	return *new(jwa.ContentEncryptionAlgorithm), false
}

func (h *stdHeaders) ContentType() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) Critical() ([]string, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *stdHeaders) EncapsulatedKey() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *stdHeaders) EphemeralPublicKey() (jwk.Key, bool) {
	_ = "STUB: not implemented"
	return *new(jwk.Key), false
}

func (h *stdHeaders) JWK() (jwk.Key, bool) { _ = "STUB: not implemented"; return *new(jwk.Key), false }

func (h *stdHeaders) JWKSetURL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) KeyID() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) PSKID() ([]byte, bool) { _ = "STUB: not implemented"; return nil, false }

func (h *stdHeaders) Type() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) X509CertChain() (*cert.Chain, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func (h *stdHeaders) X509CertThumbprint() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *stdHeaders) X509CertThumbprintS256() (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

func (h *stdHeaders) X509URL() (string, bool) { _ = "STUB: not implemented"; return "", false }

func (h *stdHeaders) clear() { _ = "STUB: not implemented"; return }

func (h *stdHeaders) isZero() bool { _ = "STUB: not implemented"; return false }

func (h *stdHeaders) PrivateParams() map[string]any { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) Has(name string) bool { _ = "STUB: not implemented"; return false }

func (h *stdHeaders) Field(name string) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (h *stdHeaders) Set(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) setNoLock(name string, value any) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) Remove(key string) error { _ = "STUB: not implemented"; return nil }

func (h *stdHeaders) UnmarshalJSON(buf []byte) error { _ = "STUB: not implemented"; return nil }

// consume closing '}'

func (h *stdHeaders) Keys() []string { _ = "STUB: not implemented"; return nil }

func (dst *stdHeaders) cloneFrom(src *stdHeaders) { _ = "STUB: not implemented"; return }

type fieldPair struct {
	Name  string
	Value any
}

type fieldPairList struct {
	pairs []fieldPair
}

var fieldPairPool = sync.Pool{
	New: func() any {
		return &fieldPairList{pairs: make([]fieldPair, 0, 16)}
	},
}

func getFieldPairList() *fieldPairList {
	_ = "STUB: not implemented"
	//nolint:forcetypeassert
	return nil
}

func putFieldPairList(l *fieldPairList) { _ = "STUB: not implemented"; return }

func fieldPairLess(a, b fieldPair) int { _ = "STUB: not implemented"; return 0 }

func writeQuotedKey(buf *bytes.Buffer, key string) { _ = "STUB: not implemented"; return }

func (h *stdHeaders) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
